import "../styles/UserDashboard.css";
import {
  RadarChart,
  Radar,
  PolarGrid,
  PolarAngleAxis,
  ResponsiveContainer,
} from "recharts";
import { useEffect, useState } from "react";
import { getHealthLogs } from "../services/healthService";
import jsPDF from "jspdf";

export default function UserDashboard() {

  const [logs, setLogs] = useState([]);

  useEffect(() => {
    const fetchLogs = async () => {
      try {
        const data = await getHealthLogs();

        /* ensure latest log is always last */

        const sortedLogs = (data || []).sort(
          (a, b) => new Date(a.createdAt) - new Date(b.createdAt)
        );

        setLogs(sortedLogs);

      } catch (err) {
        console.error(err);
      }
    };

    fetchLogs();
  }, []);

  /* USER */

  let user = null;

  try {
    const storedUser = localStorage.getItem("user");
    if (storedUser) user = JSON.parse(storedUser);
  } catch {
    console.error("Invalid user data");
  }

  /* LATEST HEALTH DATA */

  const latest = logs.length > 0 ? logs[logs.length - 1] : null;

  /* RADAR CHART DATA */

  const radarData = latest
    ? [
        { metric: "Sleep", value: (latest.sleepHours || 0) * 10 },
        { metric: "Activity", value: (latest.steps || 0) / 1000 },
        { metric: "Hydration", value: (latest.waterIntake || 0) * 10 },
        { metric: "Stress", value: 10 - (latest.stressLevel || 0) },
        { metric: "Heart", value: 100 - (latest.heartRate || 0) / 2 },
      ]
    : [];

  /* HEALTH STATUS */

  const getHealthStatus = () => {

    if (!latest) return "No Data";

    if (latest.healthScore >= 85) return "Excellent";
    if (latest.healthScore >= 70) return "Good";
    if (latest.healthScore >= 50) return "Average";

    return "Needs Attention";
  };

  const statusClass = getHealthStatus()
    .toLowerCase()
    .replace(" ", "-");

  /* PDF REPORT */

  const generateReport = () => {

    if (!latest) {
      alert("No health data available");
      return;
    }

    const doc = new jsPDF();

    const today = new Date().toLocaleDateString();

    doc.setFontSize(22);
    doc.setTextColor(109, 40, 217);
    doc.text("AI Health Report", 20, 25);

    doc.setFontSize(11);
    doc.setTextColor(100);
    doc.text(`Generated on: ${today}`, 20, 35);

    doc.setDrawColor(200);
    doc.line(20, 40, 190, 40);

    doc.setFontSize(16);
    doc.setTextColor(0);
    doc.text("Health Summary", 20, 55);

    doc.setFontSize(12);

    doc.text(`BMI: ${latest.bmi?.toFixed(1) || "--"}`, 20, 70);
    doc.text(`Heart Rate: ${latest.heartRate || "--"} bpm`, 20, 80);
    doc.text(`Sleep Hours: ${latest.sleepHours || "--"} hrs`, 20, 90);
    doc.text(`Steps: ${latest.steps || "--"}`, 20, 100);
    doc.text(`Water Intake: ${latest.waterIntake || "--"} L`, 20, 110);
    doc.text(`SpO2 Level: ${latest.spo2 || "--"}%`, 20, 120);
    doc.text(`Stress Level: ${latest.stressLevel || "--"}/10`, 20, 130);

    doc.setFontSize(16);
    doc.setTextColor(109, 40, 217);
    doc.text("Overall Health Score", 20, 150);

    doc.setFontSize(26);
    doc.text(`${latest.healthScore || "--"} / 100`, 20, 165);

    doc.setFontSize(13);
    doc.setTextColor(0);
    doc.text(`Status: ${getHealthStatus()}`, 20, 180);

    doc.setDrawColor(200);
    doc.line(20, 190, 190, 190);

    doc.setFontSize(15);
    doc.text("AI Recommendation", 20, 205);

    let recommendation =
      "Your health indicators are stable. Maintain regular exercise, hydration and balanced sleep.";

    if (latest.sleepHours < 6) {
      recommendation =
        "Your sleep duration is below recommended levels. Improving sleep habits will support better recovery.";
    }

    if (latest.steps < 4000) {
      recommendation =
        "Your activity levels are low. Increasing daily movement can improve cardiovascular health.";
    }

    doc.setFontSize(12);

    doc.text(
      doc.splitTextToSize(recommendation, 170),
      20,
      220
    );

    doc.setFontSize(10);
    doc.setTextColor(120);

    doc.text(
      "Generated by AI Health Monitoring System",
      20,
      280
    );

    doc.save("AI_Health_Report.pdf");
  };

  return (

    <div className="dashboard">

      {/* HEADER */}

      <div className="dashboard-header">
        <h1>
          Welcome Back {user?.name || "User"} !!
        </h1>
        <p>Your AI-powered health overview</p>
      </div>


      {/* STATUS CARD */}

      <div className="status-card">

        <div className="status-info">

          <h3>Overall Health Status</h3>

          <span className={`status-badge ${statusClass}`}>
            {getHealthStatus()}
          </span>

          <p>
            Based on your latest recorded health metrics.
          </p>

          <button
            className="report-btn"
            onClick={generateReport}
          >
            Generate Health Report
          </button>

        </div>


        {/* QUICK METRICS */}

        <div className="quick-metrics">

          <div className="mini-card">
            <span>{latest?.bmi?.toFixed(1) || "--"}</span>
            <p>BMI</p>
          </div>

          <div className="mini-card">
            <span>{latest?.sleepHours || "--"}h</span>
            <p>Sleep</p>
          </div>

          <div className="mini-card">
            <span>{latest?.heartRate || "--"}</span>
            <p>Heart</p>
          </div>

          <div className="mini-card">
            <span>{latest?.steps || "--"}</span>
            <p>Steps</p>
          </div>

        </div>

      </div>


      {/* RADAR CHART */}

      <div className="chart-card">

        <h3>Lifestyle Balance</h3>

        <ResponsiveContainer width="100%" height={300}>

          <RadarChart data={radarData}>

            <PolarGrid />

            <PolarAngleAxis dataKey="metric" />

            <Radar
              dataKey="value"
              stroke="#6d28d9"
              fill="#6d28d9"
              fillOpacity={0.4}
            />

          </RadarChart>

        </ResponsiveContainer>

      </div>


      {/* MOTIVATION */}

      <div className="motivation-card">
        Consistency beats intensity. Small daily habits lead to long-term wellness 🚀
      </div>

    </div>

  );
}